import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Header } from "@/src/components/header/Header";
import { useEffect, useState } from "react";
import Sidebar from "@/src/components/main/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [height, setHeight] = useState();

  useEffect(() => {
    const headerHeight = document.querySelector("header").offsetHeight;

    setHeight(headerHeight);
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main
        className={`relative flex lg:w-9/12 mx-auto px-4`}
        style={{ paddingTop: height }}
      >
        <Sidebar />
      </main>
    </>
  );
}
